#!/bin/bash

#Introduction
echo -e "Sup, Jay!
\n---
\n This script will install and configure the following....
\n---
\n\tZSH
\n\t\t- New Shell because that's the future, apparently.
\n\tOh-My-ZSH
\n\t\t- Package manager for ZSH
\n\ttmux
\n\t\t- An awesome terminal window manager
\n\tPowerline fonts
\n\t\t- Because apparently this is super important for a good looking functional terminal
\n\temacs
\n\t\t- A super awesome terminal text editor
\n\tSpaceMacs
\n\t\t- An extension for emacs to add VIM mode and IDE features
\n\temacs aliases
\n\t\t- Creates spacemaces alias and adds 'nw' to emacs alias."

#TODO - Get the script to stop here and add a confirmation prompt
#TODO - At some point, make it modular so i can add/drop stuff as needed
#TODO - Add some kind of reporting at the end so that i can see everything installed properly

#Let's get to work installing stuff
echo -e "----
\nInstalling GIT, ZSH and zsh-syntax-highlighting and switching to it as default"

#Installing ZSH
sudo apt-get update
sudo apt-get install zsh -y

#Install oh-my-zsh as unattended so it doesn't try to change the shell or switch to ZSH at the end.
sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

###install zsh-syntax-highlighting using oh-my-zsh plugins
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

echo -e "----
/nInstalling Powerline Fonts"

#Install Powerline Fonts
cd /tmp
git clone https://github.com/powerline/fonts.git --depth=1
cd fonts
./install.sh
cd ~/


echo -e "----/nCopying chromeOS zshrc file"


#copy the appropriate zshrc file to home directory for use
cp ~/dotfiles/Customization-Scripts/zshrc.chromeOS ~/.zshrc

echo -e "----/nInstalling pipenv and gnome-keyring"
#Installing pipenv for python dev
sudo apt-get install pipenv -y

#Installing gnome-keyring so i can stay signed into stuff
sudo apt-get install gnome-keyring

echo -e "----
/nInstalling emacs and spacemacs"
sudo apt-get install emacs -y

git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d

echo -e "----
/nInstalling Snapd and dependancies."

sudo apt install -y libsquashfuse0 squashfuse fuse snapd

echo -e "----
/nChanging default shell to ZSH."

sudo chsh -s /bin/zsh $USER
