#!/bin/bash

#Introduction
echo -e "Sup, Jay!
\n---
\n This script will install and configure the following....
\n---
\n\tFish Shell
\n\t\t- Fish shell is quite cool
\n\tPowerline fonts
\n\t\t- Because apparently this is super important for a good looking functional terminal
\n\temacs
\n\t\t- A super awesome terminal text editor
\n\tSpaceMacs
\n\t\t- An extension for emacs to add VIM mode and IDE features
\n\temacs aliases
\n\t\t- Creates spacemaces alias and adds 'nw' to emacs alias."

#TODO - Get the script to stop here and add a confirmation prompt
#TODO - At some point, make it modular so i can add/drop stuff as needed
#TODO - Add some kind of reporting at the end so that i can see everything installed properly

#Let's get to work installing stuff
echo -e "----
/nInstalling Fish Shell and oh-my-fish"

#Installs for Debian 11 since that's what's in crostini right now
echo 'deb http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_11/ /' | sudo tee /etc/apt/sources.list.d/shells:fish:release:3.list
curl -fsSL https://download.opensuse.org/repositories/shells:fish:release:3/Debian_11/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/shells_fish_release_3.gpg > /dev/null
sudo apt update
sudo apt install fish

#Installs oh-my-fish with the install script from git
curl https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install | fish

omf install agnoster
omf theme agnoster

echo -e "----
/nInstalling Powerline Fonts"

#Install Powerline Fonts
cd /tmp
git clone https://github.com/powerline/fonts.git --depth=1
cd fonts
./install.sh
cd ~/

echo -e "----/nInstalling pipenv and gnome-keyring"
#Installing pipenv for python dev
sudo apt-get install pipenv -y

#Installing gnome-keyring so i can stay signed into stuff
sudo apt-get install gnome-keyring

echo -e "----
/nInstalling emacs and spacemacs"
sudo apt-get install emacs -y

git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d

echo -e "----
/nInstalling Snapd and dependancies."

sudo apt install -y libsquashfuse0 squashfuse fuse snapd

echo -e "----
/nChanging default shell to Fish."

sudo chsh -s /bin/fish $USER
