#!/bin/bash

#Introduction
echo -e "Hi Jay. 
\n--- 
\n This script will install and configure the following.... 
\n--- 
\n\tZSH 
\n\t\t- New Shell because that's the future, apparently. 
\n\tOh-My-ZSH
\n\t\t- Package manager for ZSH
\n\tHyper Terminal 
\n\t\t- A super awesome terminal application 
\n\tPowerline fonts 
\n\t\t- Because apparently this is super important for a good looking functional terminal 
\n\tVisual Studio Code 
\n\t\t- A super awesome IDE"


mkdir ~\.temp
cd ~\.temp
#check if hyper is installed
####
#If it's not installed, download and install
wget -O  hyper.deb https://releases.hyper.is/download/deb
apt-get install -y ./hyper.deb

##### Used to install oh-my-zsh. probably should copy this template
sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"


##### Switch default shell to zsh
sudo chsh -s /usr/bin/zsh <username>

#Install Powerline Fonts
# clone
git clone https://github.com/powerline/fonts.git --depth=1
# install
cd fonts
./install.sh
# clean-up a bit
cd ..
rm -rf fonts


#### Install spaceship prompt
#Clone the repo
git clone https://github.com/denysdovhan/spaceship-prompt.git "$ZSH_CUSTOM/themes/spaceship-prompt"

#Symlink spaceship.zsh-theme to the oh-my-zsh custom themes director
ln -s "$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme" "$ZSH_CUSTOM/themes/spaceship.zsh-theme"

#copy my .zshrc file or add spaceship to the .zshrc file

###install zsh-syntax-highlighting

sudo apt-get install zsh-syntax-highlighting

