#!/bin/bash

#Introduction
echo -e "Sup, Jay!
\n---
\n This script will install and configure the following....
\n---
\n\tZSH
\n\t\t- New Shell because that's the future, apparently.
\n\tOh-My-ZSH
\n\t\t- Package manager for ZSH
\n\ttmux
\n\t\t- An awesome terminal window manager
\n\tPowerline fonts
\n\t\t- Because apparently this is super important for a good looking functional terminal
\n\temacs
\n\t\t- A super awesome terminal text editor
\n\tSpaceMacs
\n\t\t- An extension for emacs to add VIM mode and IDE features
\n\temacs aliases
\n\t\t- Creates spacemaces alias and adds 'nw' to emacs alias."

#TODO - Get the script to stop here and add a confirmation prompt
#TODO - At some point, make it modular so i can add/drop stuff as needed
#TODO - Add some kind of reporting at the end so that i can see everything installed properly

#Let's get to work installing stuff
echo -e "----
\nInstalling Homebrew, ZSH and zsh-syntax-highlighting and switching to it as default"

#Install Homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"


#Used to install oh-my-zsh. probably should copy this template
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

###install zsh-syntax-highlighting
brew install zsh-syntax-highlighting

echo -e "----
/nInstalling Powerline Fonts"

#Install Powerline Fonts
cd /tmp
git clone https://github.com/powerline/fonts.git --depth=1
cd fonts
./install.sh
cd ~/

#copy the appropriate zshrc file to home directory for use
cp ~/dotfiles/Customization-Scripts/zshrc.macOS ~/.zshrc

echo -e "----
/nInstalling tmux"
brew install tmux

echo -e "----
/nInstalling emacs and spacemacs"
brew install emacs

git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d

cp ~/dotfiles/Customization-Scripts/tmux.conf.chromeOS ~/.tmux.conf

echo -e "----
/nAdding the Gotham theme....because I AM THE NIGHT!

open ~/dotfiles/Customization-Scripts/Gotham.terminal
defaults write com.apple.terminal "Default Window Settings" "Gotham.terminal"

echo -e "----
/nTime to kill the terminal and open again... or reboot or something."
